#!/usr/bin/env bash

set -eu

# Rewrite our arguments to be `cargo build` instead of `cargo wasm`;
# this assumes that the command will always be `cargo wasm ...`. We
# capture the output directory in order to place the result file.

log="${HOME}/log"

shift # Ignore "wasm"
args=()
while (( "$#" )); do
    if [[ "$1" == "--" ]] ; then
        : # Ignore
    elif [[ "$1" == "-o" ]] ; then
        shift
        output="$1"
        echo "output=${output}" >> "${log}"
    else
        args+="$1"
    fi

    shift
done

echo "${args[@]}" >> log

# Perform our build
# https://stackoverflow.com/a/7577209/155423
#cargo "build" "--target=wasm32-unknown-unknown" ${args[@]+"${args[@]}"}

#for wasm in $(find target/ -name '*wasm' -not -path '*/deps/*'); do
#    echo "found ${wasm}" >> "${log}"
#    cp "${wasm}" "${output}"
#
#    # Convert to textual format, demangling as we go
##    wasm-tools demangle "${wasm}" -t -o "${output}.wat"
##    cp "${output}.wat" "${output}"
#done

wasm-pack "build" "--target=web"  "--mode" "no-install" ${args[@]+"${args[@]}"} "--" "--offline"
rm "pkg/.gitignore"
tar -cvf "${output}" "-C" "pkg/" "."
